# Generated by Django 5.0 on 2024-01-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_hotelbooking_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotelbooking',
            table='booking_hotelbooking',
        ),
    ]
