# Generated by Django 5.0 on 2024-01-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_hotelbooking_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
