# Generated by Django 5.0 on 2024-01-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_alter_hotelbooking_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='is_cancelled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
