# Generated by Django 5.0 on 2024-01-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
