# Generated by Django 5.0 on 2024-01-09 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_multiimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='multiimage',
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiimage', models.ImageField(upload_to='hotel_multi_images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiimage', to='hotels.hotel')),
            ],
        ),
    ]
