# Generated by Django 5.0 on 2024-01-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_roomtype_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='hotels.room'),
        ),
    ]
