# Generated by Django 5.0 on 2024-01-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_room_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='count',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
