# Generated by Django 5.0 on 2024-01-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_alter_hotel_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='ratings',
        ),
    ]
