# Generated by Django 5.0 on 2024-01-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_alter_hotel_latitude_alter_hotel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=31, max_digits=31, null=True),
        ),
    ]
