# Generated by Django 5.0 on 2024-01-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_alter_hotel_latitude_alter_hotel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=31, null=True),
        ),
    ]
