# Generated by Django 5.0 on 2024-02-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_alter_hotel_latitude_alter_hotel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='not_available_dates',
            field=models.JSONField(default=list, null=True),
        ),
    ]
