# Generated by Django 5.0 on 2024-02-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0026_alter_roomtype_not_available_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='not_available_dates',
        ),
    ]
