# Generated by Django 5.0 on 2024-02-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0027_remove_roomtype_not_available_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='not_available_dates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
