# Generated by Django 5.0 on 2024-02-06 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0028_roomtype_not_available_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='not_available_dates',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None),
        ),
    ]
