# Generated by Django 5.0 on 2024-03-03 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0030_alter_hotel_latitude_alter_hotel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='price_per_night',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_types', to='hotels.room'),
        ),
    ]
