# Generated by Django 5.0 on 2024-03-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0031_roomtype_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='price_per_night',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
