# Generated by Django 5.0 on 2024-02-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_chats_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats',
            options={'ordering': ['date'], 'verbose_name_plural': 'Chats'},
        ),
    ]
