# Generated by Django 5.0 on 2024-02-09 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_chats_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
