# Generated by Django 5.0 on 2024-02-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_verified_profile_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_verified',
            new_name='verified',
        ),
    ]
